package th.ac.ku.kps.eng.cpe.edu.project.model;
// Generated Oct 10, 2023, 5:36:31 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private Integer areaId;
	private int row;
	private int col;
	@JsonIgnore
	private Set reservations = new HashSet(0);

	public Area() {
	}

	public Area(int row, int col) {
		this.row = row;
		this.col = col;
	}

	public Area(int row, int col, Set reservations) {
		this.row = row;
		this.col = col;
		this.reservations = reservations;
	}

	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public int getRow() {
		return this.row;
	}

	public void setRow(int row) {
		this.row = row;
	}

	public int getCol() {
		return this.col;
	}

	public void setCol(int col) {
		this.col = col;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
