package th.ac.ku.kps.eng.cpe.edu.project.model;
// Generated Oct 10, 2023, 5:36:31 PM by Hibernate Tools 5.6.3.Final

/**
 * Likestore generated by hbm2java
 */
public class Likestore implements java.io.Serializable {

	private Integer likeId;
	private Store store;
	private User user;

	public Likestore() {
	}

	public Likestore(Store store, User user) {
		this.store = store;
		this.user = user;
	}

	public Integer getLikeId() {
		return this.likeId;
	}

	public void setLikeId(Integer likeId) {
		this.likeId = likeId;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
