package th.ac.ku.kps.eng.cpe.edu.project.model;
// Generated Oct 11, 2023, 1:40:25 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer reservationId;
	private Area area;
	private Store store;
	private Date startDate;
	private Date endDate;
	private String type;

	public Reservation() {
	}

	public Reservation(Area area, Store store, Date startDate, Date endDate, String type) {
		this.area = area;
		this.store = store;
		this.startDate = startDate;
		this.endDate = endDate;
		this.type = type;
	}

	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
