package th.ac.ku.kps.eng.cpe.edu.project.model;
// Generated Oct 10, 2023, 5:36:31 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	@JsonIgnore
	private User user;
	private String name;
	private String phone;
	private String description;
	private String type;
	private String imgPath;
	@JsonIgnore
	private List<Likestore> likestores = new ArrayList<Likestore>();
	@JsonIgnore
	private List<Reservation> reservations = new ArrayList<Reservation>();

	public Store() {
	}

	public Store(User user, String name, String phone, String description, String type, String imgPath) {
		this.user = user;
		this.name = name;
		this.phone = phone;
		this.description = description;
		this.type = type;
		this.imgPath = imgPath;
	}

	public Store(User user, String name, String phone, String description, String type, String imgPath, List<Likestore> likestores,
			List<Reservation> reservations) {
		this.user = user;
		this.name = name;
		this.phone = phone;
		this.description = description;
		this.type = type;
		this.imgPath = imgPath;
		this.likestores = likestores;
		this.reservations = reservations;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public List<Likestore> getLikestores() {
		return this.likestores;
	}

	public void setLikestores(List<Likestore> likestores) {
		this.likestores = likestores;
	}

	public List<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

}
